### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by krisdb2009** [belowaverage-org/SuperGrate#35]
- [x] listUsers box view modes option.
- [x] Icons on dialog windows.
- [x] Fix size calculator.
- [x] Right click menu in listUsers.
- [x] Disable settings menu when running.
- [x] Move Misc.MainMenuSetState to Win32Styles.cs
- [x] Get column sorting to work.
- [x] Display error if "sid" file is missing when trying to restore from store.
- [x] Change the user-list icons in the store depending on weather or not a profile was ever restored.
- [x] Add confirmation to delete users!

**Comment by krisdb2009** [comment]
Finished all tasks.
